"""Reschedule recommender — rule-based candidate generation + ML-ready ranking.

Called ONLY when the schedule_adjustment category is selected. The division of
labour is deliberate and matches the spec:

    * Candidate *times* are generated by rule-based calendar logic.
    * A weighted, ML-ready scoring function only RANKS those candidates.
      (No model invents times.)

Pipeline:
    target selection -> adjustability check -> working-hours candidate gen
    -> hard-constraint conflict filtering -> feature extraction
    -> weighted scoring -> 0..1 normalization -> reason/model_basis/buttons.

Never raises. No candidates -> empty list (caller still returns 200).
Every candidate keeps requires_user_confirmation = true; nothing is auto-applied.

Public API:
    load_reschedule_rules() -> dict
    recommend(schedule_context, user_profile=None, target_event_id=None,
              emotion_state=None) -> list[dict]
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta
from functools import lru_cache
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from backend.core.config import settings
from backend.services import llm_service

_RULES_PATH = Path(__file__).resolve().parents[1] / "rules" / "reschedule_rules.json"

# 설명 문장 최대 길이(초과 시 규칙 reason 유지).
_RESCHEDULE_REASON_MAX_LEN = 120


def _llm_reason(candidate: dict, events_count: int) -> Optional[str]:
    """이미 규칙으로 계산된 근거(reason/시각/제목)만 자연스러운 한 문장으로 바꾼다.
    LLM은 시간·우선순위·충돌을 새로 판단하지 않는다(계산은 규칙 담당). 실패/길이초과
    시 None → 호출부는 규칙 reason 유지."""
    facts = candidate.get("reason", "")
    title = candidate.get("title", "")
    prompt = (
        f"제안: {title}\n"
        f"이미 계산된 근거: {facts}\n"
        f"오늘 일정 수: {events_count}개\n"
        "위 '근거'만 사용해 이 시간으로 옮기길 권하는 자연스러운 한국어 한 문장을 만들어줘. "
        "시간·우선순위·충돌을 새로 판단하거나 새 숫자를 지어내지 말고, 주어진 사실만 풀어써. 문장만 출력."
    )
    text = llm_service.generate(
        prompt,
        system="너는 일정 비서야. 주어진 근거로 제안 문장 하나만 만들어. 계산·판단 금지.",
        max_tokens=120,
    )
    if not text:
        return None
    text = text.strip().splitlines()[0].strip()
    if not text or len(text) > _RESCHEDULE_REASON_MAX_LEN:
        return None
    return text


@lru_cache(maxsize=1)
def load_reschedule_rules() -> dict:
    with open(_RULES_PATH, encoding="utf-8") as f:
        return json.load(f)


def _parse_dt(value: Optional[str]) -> Optional[datetime]:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except (ValueError, AttributeError):
        return None


def _block_of(hour: int, blocks: dict) -> Optional[str]:
    for name, (lo, hi) in blocks.items():
        if lo <= hour <= hi:
            return name
    return None


def _select_target(
    events: List[dict], rules: dict, target_event_id: Optional[str]
) -> Optional[dict]:
    """Find the event to move. Explicit id wins; else first adjustable event."""
    non_adj = set(rules["non_adjustable_categories"])
    adjustable = set(rules["adjustable_priorities"])

    def _is_adjustable(ev: dict) -> bool:
        if ev.get("is_fixed"):
            return False
        if (ev.get("category") or "").lower() in non_adj:
            return False
        if (ev.get("priority") or "").lower() not in adjustable:
            return False
        return True

    if target_event_id is not None:
        for ev in events:
            if ev.get("id") == target_event_id:
                return ev if _is_adjustable(ev) else None
        return None

    for ev in events:
        if _is_adjustable(ev):
            return ev
    return None


def _busy_intervals(
    events: List[dict], exclude_id: Optional[str]
) -> List[Tuple[datetime, datetime]]:
    out = []
    for ev in events:
        if exclude_id is not None and ev.get("id") == exclude_id:
            continue
        s, e = _parse_dt(ev.get("start_time")), _parse_dt(ev.get("end_time"))
        if s and e and s < e:
            out.append((s, e))
    return out


def _overlaps(s: datetime, e: datetime, busy: List[Tuple[datetime, datetime]]) -> bool:
    return any(s < be and bs < e for bs, be in busy)


def _nearest_gap_after(
    end: datetime, busy: List[Tuple[datetime, datetime]]
) -> Optional[int]:
    """Minutes from `end` to the next busy start (None if nothing after)."""
    laters = [bs for bs, _ in busy if bs >= end]
    if not laters:
        return None
    return int((min(laters) - end).total_seconds() // 60)


def _near_high_priority(
    s: datetime, e: datetime, events: List[dict], exclude_id: Optional[str]
) -> bool:
    for ev in events:
        if exclude_id is not None and ev.get("id") == exclude_id:
            continue
        if (ev.get("priority") or "").lower() != "high":
            continue
        bs, be = _parse_dt(ev.get("start_time")), _parse_dt(ev.get("end_time"))
        if not bs or not be:
            continue
        # within 30 minutes on either side
        if s - timedelta(minutes=30) < be and bs < e + timedelta(minutes=30):
            return True
    return False


def recommend(
    schedule_context: Optional[dict],
    user_profile: Optional[dict] = None,
    target_event_id: Optional[str] = None,
    emotion_state: Optional[str] = None,
) -> List[dict]:
    rules = load_reschedule_rules()
    if not schedule_context:
        return []

    events = schedule_context.get("today_schedule", []) or []
    now = _parse_dt(schedule_context.get("current_time"))

    target = _select_target(events, rules, target_event_id)
    if target is None:
        return []

    t_start, t_end = _parse_dt(target.get("start_time")), _parse_dt(target.get("end_time"))
    if not t_start or not t_end or t_start >= t_end:
        return []
    duration = int((t_end - t_start).total_seconds() // 60)
    if duration <= 0:
        return []

    day = (now or t_start).replace(hour=0, minute=0, second=0, microsecond=0)
    wh = rules["working_hours"]
    step = rules["candidate_step_minutes"]
    blocks = {k: tuple(v) for k, v in rules["time_blocks"].items()}
    weights = rules["weights"]
    profile = user_profile or {}
    preferred_blocks = set(profile.get("preferred_time_blocks", []) or [])
    preferred_hours = set(profile.get("preferred_study_hours", []) or [])

    busy = _busy_intervals(events, exclude_id=target.get("id"))

    win_start = day + timedelta(hours=wh["start_hour"])
    win_end = day + timedelta(hours=wh["end_hour"])
    # do not propose a slot in the past
    lower_bound = max(win_start, now) if now else win_start

    scored: List[dict] = []
    cursor = win_start
    while cursor + timedelta(minutes=duration) <= win_end:
        s = cursor
        e = cursor + timedelta(minutes=duration)
        cursor = cursor + timedelta(minutes=step)

        if s < lower_bound:
            continue
        # hard constraint: skip anything that starts at the target's own slot
        if s == t_start:
            continue
        # hard constraint: no overlap with existing schedules
        if _overlaps(s, e, busy):
            continue

        hour = s.hour
        block = _block_of(hour, blocks)
        gap_after = _nearest_gap_after(e, busy)
        is_too_late = hour >= rules["too_late_hour"]
        near_high = _near_high_priority(s, e, events, target.get("id"))

        features = {
            "candidate_start_hour": hour,
            "candidate_day_of_week": s.weekday(),
            "duration_minutes": duration,
            "gap_before_minutes": None,
            "gap_after_minutes": gap_after,
            "is_morning": block == "morning",
            "is_afternoon": block == "afternoon",
            "is_evening": block == "evening",
            "is_late_night": block == "late_night",
            "is_too_late": is_too_late,
            "event_category": target.get("category"),
            "event_priority": target.get("priority"),
            "schedule_load_score": round(len(events) / 10.0, 2),
            "preferred_time_block_match": block in preferred_blocks if block else False,
            "preferred_hour_match": hour in preferred_hours,
            "near_high_priority_event": near_high,
            "emotion_state": emotion_state,
        }

        # ---- weighted scoring (ML-ready: linear over binary/continuous feats) ----
        raw = 0.0
        raw += weights["no_conflict"] * 1.0  # reached here => no conflict
        raw += weights["preferred_time_block_match"] * (1.0 if features["preferred_time_block_match"] else 0.0)
        raw += weights["preferred_hour_match"] * (1.0 if features["preferred_hour_match"] else 0.0)
        raw += weights["gap_after_ok"] * (1.0 if (gap_after is None or gap_after >= 15) else 0.0)
        raw += weights["not_too_late"] * (0.0 if is_too_late else 1.0)
        raw += weights["not_near_high_priority"] * (0.0 if near_high else 1.0)
        score = round(max(0.0, min(1.0, raw)), 2)  # weights sum to 1.0 -> already normalized

        reason_bits = ["기존 일정과 충돌하지 않습니다"]
        if features["preferred_time_block_match"] or features["preferred_hour_match"]:
            reason_bits.append("선호하는 시간대와 잘 맞습니다")
        if gap_after is None or gap_after >= 15:
            reason_bits.append("다음 일정 전까지 여유 시간이 있습니다")
        if not is_too_late:
            reason_bits.append("늦은 시간대가 아닙니다")
        reason = ", ".join(reason_bits) + "."

        model_basis_features = ["기존 일정과 충돌 없음"]
        if features["preferred_time_block_match"] or features["preferred_hour_match"]:
            model_basis_features.append("사용자 선호 시간대와 일치")
        if gap_after is None or gap_after >= 15:
            model_basis_features.append("다음 일정 전 여유 시간 확보")
        if not is_too_late:
            model_basis_features.append("늦은 시간대가 아님")

        title = f"{target.get('title') or '일정'}을(를) {s.strftime('%H:%M')}로 옮기기"

        scored.append(
            {
                "category": "schedule_adjustment",
                "solution_type": "reschedule_low_priority",
                "title": title,
                "reason": reason,
                "score": score,
                "model_basis": {
                    "method": "ml_ready_weighted_ranking",
                    "features": model_basis_features,
                    "feature_vector": features,
                },
                "action_buttons": ["이 시간으로 변경", "다른 시간 보기", "그대로 둘게요"],
                "requires_user_confirmation": True,
                "_start_hour": hour,  # sort tiebreaker, stripped below
            }
        )

    # highest score first, then earlier start time
    scored.sort(key=lambda c: (-c["score"], c["_start_hour"]))
    for c in scored:
        c.pop("_start_hour", None)

    # keep a focused shortlist
    shortlist = scored[:5]

    # 설명 문장만 LLM로 자연스럽게(최상위 후보 1개만 → 비용 1콜). 계산/후보/점수는
    # 위 규칙 결과 그대로 유지되며, 실패 시 규칙 reason 을 그대로 쓴다.
    if shortlist and settings.ENABLE_LLM_RESCHEDULE and llm_service.is_enabled():
        try:
            nice = _llm_reason(shortlist[0], len(events))
        except Exception:
            nice = None
        if nice:
            shortlist[0]["reason"] = nice

    return shortlist
