name: frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.12.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTML 화면 WebView
  webview_flutter: ^4.10.0

  # API
  dio: ^5.9.0

  # 상태관리
  provider: ^6.1.5

  # 환경변수
  flutter_dotenv: ^5.2.1

  # 캘린더
  table_calendar: ^3.2.0

  # 위치
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3

  # 권한
  permission_handler: ^12.0.1

  # 음성
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3

  # 알림
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0

  # 로컬 저장
  shared_preferences: ^2.5.3

  # 이미지
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/html/